/* Generated by itemis CREATE code generator. */

import com.yakindu.core.IEventDriven;
import com.yakindu.core.IStatemachine;
import com.yakindu.core.ITimed;
import com.yakindu.core.ITimerService;
import java.util.LinkedList;
import java.util.Queue;

public class Microwave implements ITimed, IEventDriven {
	public enum State {
		MICROWAVE_IDLE,
		MICROWAVE_COOKING,
		MICROWAVE_MODE,
		MICROWAVE_MODE_R1_HIGH,
		MICROWAVE_MODE_R1_LOW,
		MICROWAVE_WAITING,
		MICROWAVE_SETTINGTIME,
		MICROWAVE_RESTARTCOOKING,
		MICROWAVE_FINISHED,
		MICROWAVE_FINISHED_R1_BIP_ON,
		MICROWAVE_FINISHED_R1_BIP_OFF,
		OPEN_CLOSE_DOOR_DOOROPEN,
		OPEN_CLOSE_DOOR_DOORCLOSED,
		$NULLSTATE$
	};
	
	private final State[] stateVector = new State[2];
	
	private ITimerService timerService;
	
	private final boolean[] timeEvents = new boolean[4];
	
	private Queue<Runnable> inEventQueue = new LinkedList<Runnable>();
	private long enteredTime;
	
	protected long getEnteredTime() {
		return enteredTime;
	}
	
	protected void setEnteredTime(long value) {
		this.enteredTime = value;
	}
	
	
	private boolean isDoorClose;
	
	protected boolean getIsDoorClose() {
		return isDoorClose;
	}
	
	protected void setIsDoorClose(boolean value) {
		this.isDoorClose = value;
	}
	
	
	private long remainingTime;
	
	protected long getRemainingTime() {
		return remainingTime;
	}
	
	protected void setRemainingTime(long value) {
		this.remainingTime = value;
	}
	
	
	private boolean isExecuting;
	
	protected boolean getIsExecuting() {
		return isExecuting;
	}
	
	protected void setIsExecuting(boolean value) {
		this.isExecuting = value;
	}
	private long stateConfVectorPosition;
	
	protected long getStateConfVectorPosition() {
		return stateConfVectorPosition;
	}
	
	protected void setStateConfVectorPosition(long value) {
		this.stateConfVectorPosition = value;
	}
	public Microwave() {
		for (int i = 0; i < 2; i++) {
			stateVector[i] = State.$NULLSTATE$;
		}
		
		clearInEvents();
		
		/* Default init sequence for statechart microwave */
		setPower(0l);
		setEnteredTime(0l);
		setIsDoorClose(true);
		setRemainingTime(0l);
		
		isExecuting = false;
	}
	
	public void enter() {
		/* Activates the state machine. */
		if (timerService == null) {
			throw new IllegalStateException("Timer service must be set.");
		}
		if (this.operationCallback == null) {
			throw new IllegalStateException("Operation callback must be set.");
		}
		
		{
		};
		if (getIsExecuting()) {
			return;
		}
		isExecuting = true;
		/* Default enter sequence for statechart microwave */
		enterSequence_Microwave_default();
		enterSequence_Open_Close_Door_default();
		isExecuting = false;
	}
	
	public void exit() {
		/* Deactivates the state machine. */
		if (getIsExecuting()) {
			return;
		}
		isExecuting = true;
		/* Default exit sequence for statechart microwave */
		exitSequence_Microwave();
		stateVector[0] = State.$NULLSTATE$;
		stateConfVectorPosition = 0;
		exitSequence_Open_Close_Door();
		stateVector[1] = State.$NULLSTATE$;
		stateConfVectorPosition = 1;
		isExecuting = false;
	}
	
	/**
	 * @see IStatemachine#isActive()
	 */
	public boolean isActive() {
		return stateVector[0] != State.$NULLSTATE$||stateVector[1] != State.$NULLSTATE$;
	}
	
	/** 
	* Always returns 'false' since this state machine can never become final.
	*
	* @see IStatemachine#isFinal()
	*/
	public boolean isFinal() {
		return false;
	}
	private void clearInEvents() {
		high = false;
		low = false;
		digit = false;
		timer = false;
		start = false;
		stop = false;
		open = false;
		close = false;
		timeEvents[0] = false;
		timeEvents[1] = false;
		timeEvents[2] = false;
		timeEvents[3] = false;
	}
	
	private void microStep() {
		long transitioned = -1l;
		stateConfVectorPosition = 0l;
		switch (stateVector[0]) {
		case MICROWAVE_IDLE:
			transitioned = microwave_Idle_react(transitioned);
			break;
		case MICROWAVE_COOKING:
			transitioned = microwave_Cooking_react(transitioned);
			break;
		case MICROWAVE_MODE_R1_HIGH:
			transitioned = microwave_Mode_r1_High_react(transitioned);
			break;
		case MICROWAVE_MODE_R1_LOW:
			transitioned = microwave_Mode_r1_Low_react(transitioned);
			break;
		case MICROWAVE_WAITING:
			transitioned = microwave_Waiting_react(transitioned);
			break;
		case MICROWAVE_SETTINGTIME:
			transitioned = microwave_SettingTime_react(transitioned);
			break;
		case MICROWAVE_RESTARTCOOKING:
			transitioned = microwave_RestartCooking_react(transitioned);
			break;
		case MICROWAVE_FINISHED_R1_BIP_ON:
			transitioned = microwave_Finished_r1_Bip_On_react(transitioned);
			break;
		case MICROWAVE_FINISHED_R1_BIP_OFF:
			transitioned = microwave_Finished_r1_Bip_Off_react(transitioned);
			break;
		default:
			break;
		}
		if (getStateConfVectorPosition()<1l) {
			switch (stateVector[1]) {
			case OPEN_CLOSE_DOOR_DOOROPEN:
				open_Close_Door_DoorOpen_react(transitioned);
				break;
			case OPEN_CLOSE_DOOR_DOORCLOSED:
				open_Close_Door_DoorClosed_react(transitioned);
				break;
			default:
				break;
			}
		}
	}
	
	private void runCycle() {
		/* Performs a 'run to completion' step. */
		if (timerService == null) {
			throw new IllegalStateException("Timer service must be set.");
		}
		if (this.operationCallback == null) {
			throw new IllegalStateException("Operation callback must be set.");
		}
		
		if (getIsExecuting()) {
			return;
		}
		isExecuting = true;
		nextEvent();
		do { 
			microStep();
			clearInEvents();
		} while (nextEvent());
		isExecuting = false;
	}
	
	protected boolean nextEvent() {
		if(!inEventQueue.isEmpty()) {
			inEventQueue.poll().run();
			return true;
		}
		return false;
	}
	/**
	* Returns true if the given state is currently active otherwise false.
	*/
	public boolean isStateActive(State state) {
	
		switch (state) {
		case MICROWAVE_IDLE:
			return stateVector[0] == State.MICROWAVE_IDLE;
		case MICROWAVE_COOKING:
			return stateVector[0] == State.MICROWAVE_COOKING;
		case MICROWAVE_MODE:
			return stateVector[0].ordinal() >= State.
					MICROWAVE_MODE.ordinal()&& stateVector[0].ordinal() <= State.MICROWAVE_MODE_R1_LOW.ordinal();
		case MICROWAVE_MODE_R1_HIGH:
			return stateVector[0] == State.MICROWAVE_MODE_R1_HIGH;
		case MICROWAVE_MODE_R1_LOW:
			return stateVector[0] == State.MICROWAVE_MODE_R1_LOW;
		case MICROWAVE_WAITING:
			return stateVector[0] == State.MICROWAVE_WAITING;
		case MICROWAVE_SETTINGTIME:
			return stateVector[0] == State.MICROWAVE_SETTINGTIME;
		case MICROWAVE_RESTARTCOOKING:
			return stateVector[0] == State.MICROWAVE_RESTARTCOOKING;
		case MICROWAVE_FINISHED:
			return stateVector[0].ordinal() >= State.
					MICROWAVE_FINISHED.ordinal()&& stateVector[0].ordinal() <= State.MICROWAVE_FINISHED_R1_BIP_OFF.ordinal();
		case MICROWAVE_FINISHED_R1_BIP_ON:
			return stateVector[0] == State.MICROWAVE_FINISHED_R1_BIP_ON;
		case MICROWAVE_FINISHED_R1_BIP_OFF:
			return stateVector[0] == State.MICROWAVE_FINISHED_R1_BIP_OFF;
		case OPEN_CLOSE_DOOR_DOOROPEN:
			return stateVector[1] == State.OPEN_CLOSE_DOOR_DOOROPEN;
		case OPEN_CLOSE_DOOR_DOORCLOSED:
			return stateVector[1] == State.OPEN_CLOSE_DOOR_DOORCLOSED;
		default:
			return false;
		}
	}
	
	public void setTimerService(ITimerService timerService) {
		this.timerService = timerService;
	}
	
	public ITimerService getTimerService() {
		return timerService;
	}
	
	public void raiseTimeEvent(int eventID) {
		inEventQueue.add(() -> {
			timeEvents[eventID] = true;
		});
		runCycle();
	}
	
	
	public interface OperationCallback {
	
		public void displayTime(long t);
		
		public void display(String msg);
		
		public void clearDisplay();
		
		public void cook();
		
		public void stopCook();
		
		public void beepOn();
		
		public void beepOff();
		
		public void closeDoor();
		
		public void openDoor();
		
	}
	
	private OperationCallback operationCallback;
	
	public void setOperationCallback(OperationCallback operationCallback) {
		this.operationCallback = operationCallback;
	}
	
	private boolean high;
	
	
	public void raiseHigh() {
		inEventQueue.add(() -> {
			high = true;
		});
		runCycle();
	}
	
	private boolean low;
	
	
	public void raiseLow() {
		inEventQueue.add(() -> {
			low = true;
		});
		runCycle();
	}
	
	private boolean digit;
	
	private long digitValue;
	
	
	public void raiseDigit(final long value) {
		inEventQueue.add(() -> {
			digitValue = value;
			digit = true;
		});
		runCycle();
	}
	protected long getDigitValue() {
		if (! digit ) 
			throw new IllegalStateException("Illegal event value access. Event Digit is not raised!");
		return digitValue;
	}
	
	private boolean timer;
	
	
	public void raiseTimer() {
		inEventQueue.add(() -> {
			timer = true;
		});
		runCycle();
	}
	
	private boolean start;
	
	
	public void raiseStart() {
		inEventQueue.add(() -> {
			start = true;
		});
		runCycle();
	}
	
	private boolean stop;
	
	
	public void raiseStop() {
		inEventQueue.add(() -> {
			stop = true;
		});
		runCycle();
	}
	
	private boolean open;
	
	
	public void raiseOpen() {
		inEventQueue.add(() -> {
			open = true;
		});
		runCycle();
	}
	
	private boolean close;
	
	
	public void raiseClose() {
		inEventQueue.add(() -> {
			close = true;
		});
		runCycle();
	}
	
	private long power;
	
	public long getPower() {
		return power;
	}
	
	public void setPower(long value) {
		this.power = value;
	}
	
	/* Entry action for state 'Cooking'. */
	private void entryAction_Microwave_Cooking() {
		/* Entry action for state 'Cooking'. */
		timerService.setTimer(this, 0, (1l * 1000l), true);
	}
	
	/* Entry action for state 'High'. */
	private void entryAction_Microwave_Mode_r1_High() {
		/* Entry action for state 'High'. */
		setPower(1l);
		operationCallback.display("High");
	}
	
	/* Entry action for state 'Low'. */
	private void entryAction_Microwave_Mode_r1_Low() {
		/* Entry action for state 'Low'. */
		setPower(2l);
		operationCallback.display("Low");
	}
	
	/* Entry action for state 'Waiting'. */
	private void entryAction_Microwave_Waiting() {
		/* Entry action for state 'Waiting'. */
		operationCallback.display("Waiting");
		operationCallback.stopCook();
	}
	
	/* Entry action for state 'SettingTime'. */
	private void entryAction_Microwave_SettingTime() {
		/* Entry action for state 'SettingTime'. */
		setEnteredTime(0l);
		operationCallback.displayTime(0l);
	}
	
	/* Entry action for state 'RestartCooking'. */
	private void entryAction_Microwave_RestartCooking() {
		/* Entry action for state 'RestartCooking'. */
		operationCallback.displayTime(((((getRemainingTime() / 60l)) * 100l) + ((getRemainingTime() % 60l))));
	}
	
	/* Entry action for state 'Finished'. */
	private void entryAction_Microwave_Finished() {
		/* Entry action for state 'Finished'. */
		timerService.setTimer(this, 1, (5l * 1000l), false);
		operationCallback.display("Finished");
		operationCallback.stopCook();
	}
	
	/* Entry action for state 'Bip On'. */
	private void entryAction_Microwave_Finished_r1_Bip_On() {
		/* Entry action for state 'Bip On'. */
		timerService.setTimer(this, 2, 500l, false);
		operationCallback.beepOn();
	}
	
	/* Entry action for state 'Bip Off'. */
	private void entryAction_Microwave_Finished_r1_Bip_Off() {
		/* Entry action for state 'Bip Off'. */
		timerService.setTimer(this, 3, 500l, false);
		operationCallback.beepOff();
	}
	
	/* Entry action for state 'DoorOpen'. */
	private void entryAction_Open_Close_Door_DoorOpen() {
		/* Entry action for state 'DoorOpen'. */
		operationCallback.openDoor();
		setIsDoorClose(false);
	}
	
	/* Entry action for state 'DoorClosed'. */
	private void entryAction_Open_Close_Door_DoorClosed() {
		/* Entry action for state 'DoorClosed'. */
		operationCallback.closeDoor();
		setIsDoorClose(true);
	}
	
	/* Exit action for state 'Cooking'. */
	private void exitAction_Microwave_Cooking() {
		/* Exit action for state 'Cooking'. */
		timerService.unsetTimer(this, 0);
	}
	
	/* Exit action for state 'Finished'. */
	private void exitAction_Microwave_Finished() {
		/* Exit action for state 'Finished'. */
		timerService.unsetTimer(this, 1);
	}
	
	/* Exit action for state 'Bip On'. */
	private void exitAction_Microwave_Finished_r1_Bip_On() {
		/* Exit action for state 'Bip On'. */
		timerService.unsetTimer(this, 2);
	}
	
	/* Exit action for state 'Bip Off'. */
	private void exitAction_Microwave_Finished_r1_Bip_Off() {
		/* Exit action for state 'Bip Off'. */
		timerService.unsetTimer(this, 3);
	}
	
	/* 'default' enter sequence for state Idle */
	private void enterSequence_Microwave_Idle_default() {
		/* 'default' enter sequence for state Idle */
		stateVector[0] = State.MICROWAVE_IDLE;
		stateConfVectorPosition = 0;
	}
	
	/* 'default' enter sequence for state Cooking */
	private void enterSequence_Microwave_Cooking_default() {
		/* 'default' enter sequence for state Cooking */
		entryAction_Microwave_Cooking();
		stateVector[0] = State.MICROWAVE_COOKING;
		stateConfVectorPosition = 0;
	}
	
	/* 'alt_entry' enter sequence for state Mode */
	private void enterSequence_Microwave_Mode_alt_entry() {
		/* 'alt_entry' enter sequence for state Mode */
		enterSequence_Microwave_Mode_r1_alt_entry();
	}
	
	/* 'default' enter sequence for state Mode */
	private void enterSequence_Microwave_Mode_default() {
		/* 'default' enter sequence for state Mode */
		enterSequence_Microwave_Mode_r1_default();
	}
	
	/* 'default' enter sequence for state High */
	private void enterSequence_Microwave_Mode_r1_High_default() {
		/* 'default' enter sequence for state High */
		entryAction_Microwave_Mode_r1_High();
		stateVector[0] = State.MICROWAVE_MODE_R1_HIGH;
		stateConfVectorPosition = 0;
	}
	
	/* 'default' enter sequence for state Low */
	private void enterSequence_Microwave_Mode_r1_Low_default() {
		/* 'default' enter sequence for state Low */
		entryAction_Microwave_Mode_r1_Low();
		stateVector[0] = State.MICROWAVE_MODE_R1_LOW;
		stateConfVectorPosition = 0;
	}
	
	/* 'default' enter sequence for state Waiting */
	private void enterSequence_Microwave_Waiting_default() {
		/* 'default' enter sequence for state Waiting */
		entryAction_Microwave_Waiting();
		stateVector[0] = State.MICROWAVE_WAITING;
		stateConfVectorPosition = 0;
	}
	
	/* 'default' enter sequence for state SettingTime */
	private void enterSequence_Microwave_SettingTime_default() {
		/* 'default' enter sequence for state SettingTime */
		entryAction_Microwave_SettingTime();
		stateVector[0] = State.MICROWAVE_SETTINGTIME;
		stateConfVectorPosition = 0;
	}
	
	/* 'default' enter sequence for state RestartCooking */
	private void enterSequence_Microwave_RestartCooking_default() {
		/* 'default' enter sequence for state RestartCooking */
		entryAction_Microwave_RestartCooking();
		stateVector[0] = State.MICROWAVE_RESTARTCOOKING;
		stateConfVectorPosition = 0;
	}
	
	/* 'default' enter sequence for state Finished */
	private void enterSequence_Microwave_Finished_default() {
		/* 'default' enter sequence for state Finished */
		entryAction_Microwave_Finished();
		enterSequence_Microwave_Finished_r1_default();
	}
	
	/* 'default' enter sequence for state Bip On */
	private void enterSequence_Microwave_Finished_r1_Bip_On_default() {
		/* 'default' enter sequence for state Bip On */
		entryAction_Microwave_Finished_r1_Bip_On();
		stateVector[0] = State.MICROWAVE_FINISHED_R1_BIP_ON;
		stateConfVectorPosition = 0;
	}
	
	/* 'default' enter sequence for state Bip Off */
	private void enterSequence_Microwave_Finished_r1_Bip_Off_default() {
		/* 'default' enter sequence for state Bip Off */
		entryAction_Microwave_Finished_r1_Bip_Off();
		stateVector[0] = State.MICROWAVE_FINISHED_R1_BIP_OFF;
		stateConfVectorPosition = 0;
	}
	
	/* 'default' enter sequence for state DoorOpen */
	private void enterSequence_Open_Close_Door_DoorOpen_default() {
		/* 'default' enter sequence for state DoorOpen */
		entryAction_Open_Close_Door_DoorOpen();
		stateVector[1] = State.OPEN_CLOSE_DOOR_DOOROPEN;
		stateConfVectorPosition = 1;
	}
	
	/* 'default' enter sequence for state DoorClosed */
	private void enterSequence_Open_Close_Door_DoorClosed_default() {
		/* 'default' enter sequence for state DoorClosed */
		entryAction_Open_Close_Door_DoorClosed();
		stateVector[1] = State.OPEN_CLOSE_DOOR_DOORCLOSED;
		stateConfVectorPosition = 1;
	}
	
	/* 'default' enter sequence for region Microwave */
	private void enterSequence_Microwave_default() {
		/* 'default' enter sequence for region Microwave */
		react_Microwave__entry_Default();
	}
	
	/* 'default' enter sequence for region r1 */
	private void enterSequence_Microwave_Mode_r1_default() {
		/* 'default' enter sequence for region r1 */
		react_Microwave_Mode_r1__entry_Default();
	}
	
	/* 'alt_entry' enter sequence for region r1 */
	private void enterSequence_Microwave_Mode_r1_alt_entry() {
		/* 'alt_entry' enter sequence for region r1 */
		react_Microwave_Mode_r1_alt_entry();
	}
	
	/* 'default' enter sequence for region r1 */
	private void enterSequence_Microwave_Finished_r1_default() {
		/* 'default' enter sequence for region r1 */
		react_Microwave_Finished_r1__entry_Default();
	}
	
	/* 'default' enter sequence for region Open/Close Door */
	private void enterSequence_Open_Close_Door_default() {
		/* 'default' enter sequence for region Open/Close Door */
		react_Open_Close_Door__entry_Default();
	}
	
	/* Default exit sequence for state Idle */
	private void exitSequence_Microwave_Idle() {
		/* Default exit sequence for state Idle */
		stateVector[0] = State.$NULLSTATE$;
		stateConfVectorPosition = 0;
	}
	
	/* Default exit sequence for state Cooking */
	private void exitSequence_Microwave_Cooking() {
		/* Default exit sequence for state Cooking */
		stateVector[0] = State.$NULLSTATE$;
		stateConfVectorPosition = 0;
		exitAction_Microwave_Cooking();
	}
	
	/* Default exit sequence for state Mode */
	private void exitSequence_Microwave_Mode() {
		/* Default exit sequence for state Mode */
		exitSequence_Microwave_Mode_r1();
		stateVector[0] = State.$NULLSTATE$;
		stateConfVectorPosition = 0;
	}
	
	/* Default exit sequence for state High */
	private void exitSequence_Microwave_Mode_r1_High() {
		/* Default exit sequence for state High */
		stateVector[0] = State.MICROWAVE_MODE;
		stateConfVectorPosition = 0;
	}
	
	/* Default exit sequence for state Low */
	private void exitSequence_Microwave_Mode_r1_Low() {
		/* Default exit sequence for state Low */
		stateVector[0] = State.MICROWAVE_MODE;
		stateConfVectorPosition = 0;
	}
	
	/* Default exit sequence for state Waiting */
	private void exitSequence_Microwave_Waiting() {
		/* Default exit sequence for state Waiting */
		stateVector[0] = State.$NULLSTATE$;
		stateConfVectorPosition = 0;
	}
	
	/* Default exit sequence for state SettingTime */
	private void exitSequence_Microwave_SettingTime() {
		/* Default exit sequence for state SettingTime */
		stateVector[0] = State.$NULLSTATE$;
		stateConfVectorPosition = 0;
	}
	
	/* Default exit sequence for state RestartCooking */
	private void exitSequence_Microwave_RestartCooking() {
		/* Default exit sequence for state RestartCooking */
		stateVector[0] = State.$NULLSTATE$;
		stateConfVectorPosition = 0;
	}
	
	/* Default exit sequence for state Finished */
	private void exitSequence_Microwave_Finished() {
		/* Default exit sequence for state Finished */
		exitSequence_Microwave_Finished_r1();
		stateVector[0] = State.$NULLSTATE$;
		stateConfVectorPosition = 0;
		exitAction_Microwave_Finished();
	}
	
	/* Default exit sequence for state Bip On */
	private void exitSequence_Microwave_Finished_r1_Bip_On() {
		/* Default exit sequence for state Bip On */
		stateVector[0] = State.MICROWAVE_FINISHED;
		stateConfVectorPosition = 0;
		exitAction_Microwave_Finished_r1_Bip_On();
	}
	
	/* Default exit sequence for state Bip Off */
	private void exitSequence_Microwave_Finished_r1_Bip_Off() {
		/* Default exit sequence for state Bip Off */
		stateVector[0] = State.MICROWAVE_FINISHED;
		stateConfVectorPosition = 0;
		exitAction_Microwave_Finished_r1_Bip_Off();
	}
	
	/* Default exit sequence for state DoorOpen */
	private void exitSequence_Open_Close_Door_DoorOpen() {
		/* Default exit sequence for state DoorOpen */
		stateVector[1] = State.$NULLSTATE$;
		stateConfVectorPosition = 1;
	}
	
	/* Default exit sequence for state DoorClosed */
	private void exitSequence_Open_Close_Door_DoorClosed() {
		/* Default exit sequence for state DoorClosed */
		stateVector[1] = State.$NULLSTATE$;
		stateConfVectorPosition = 1;
	}
	
	/* Default exit sequence for region Microwave */
	private void exitSequence_Microwave() {
		/* Default exit sequence for region Microwave */
		switch (stateVector[0]) {
		case MICROWAVE_IDLE:
			exitSequence_Microwave_Idle();
			break;
		case MICROWAVE_COOKING:
			exitSequence_Microwave_Cooking();
			break;
		case MICROWAVE_MODE:
			exitSequence_Microwave_Mode();
			break;
		case MICROWAVE_MODE_R1_HIGH:
			exitSequence_Microwave_Mode_r1_High();
			break;
		case MICROWAVE_MODE_R1_LOW:
			exitSequence_Microwave_Mode_r1_Low();
			break;
		case MICROWAVE_WAITING:
			exitSequence_Microwave_Waiting();
			break;
		case MICROWAVE_SETTINGTIME:
			exitSequence_Microwave_SettingTime();
			break;
		case MICROWAVE_RESTARTCOOKING:
			exitSequence_Microwave_RestartCooking();
			break;
		case MICROWAVE_FINISHED:
			exitSequence_Microwave_Finished();
			break;
		case MICROWAVE_FINISHED_R1_BIP_ON:
			exitSequence_Microwave_Finished_r1_Bip_On();
			exitAction_Microwave_Finished();
			break;
		case MICROWAVE_FINISHED_R1_BIP_OFF:
			exitSequence_Microwave_Finished_r1_Bip_Off();
			exitAction_Microwave_Finished();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region r1 */
	private void exitSequence_Microwave_Mode_r1() {
		/* Default exit sequence for region r1 */
		switch (stateVector[0]) {
		case MICROWAVE_MODE_R1_HIGH:
			exitSequence_Microwave_Mode_r1_High();
			break;
		case MICROWAVE_MODE_R1_LOW:
			exitSequence_Microwave_Mode_r1_Low();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region r1 */
	private void exitSequence_Microwave_Finished_r1() {
		/* Default exit sequence for region r1 */
		switch (stateVector[0]) {
		case MICROWAVE_FINISHED_R1_BIP_ON:
			exitSequence_Microwave_Finished_r1_Bip_On();
			break;
		case MICROWAVE_FINISHED_R1_BIP_OFF:
			exitSequence_Microwave_Finished_r1_Bip_Off();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region Open/Close Door */
	private void exitSequence_Open_Close_Door() {
		/* Default exit sequence for region Open/Close Door */
		switch (stateVector[1]) {
		case OPEN_CLOSE_DOOR_DOOROPEN:
			exitSequence_Open_Close_Door_DoorOpen();
			break;
		case OPEN_CLOSE_DOOR_DOORCLOSED:
			exitSequence_Open_Close_Door_DoorClosed();
			break;
		default:
			break;
		}
	}
	
	/* Default react sequence for initial entry  */
	private void react_Microwave_Mode_r1__entry_Default() {
		/* Default react sequence for initial entry  */
		enterSequence_Microwave_Mode_r1_High_default();
	}
	
	/* Default react sequence for initial entry alt_entry */
	private void react_Microwave_Mode_r1_alt_entry() {
		/* Default react sequence for initial entry alt_entry */
		enterSequence_Microwave_Mode_r1_Low_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_Microwave_Finished_r1__entry_Default() {
		/* Default react sequence for initial entry  */
		enterSequence_Microwave_Finished_r1_Bip_On_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_Microwave__entry_Default() {
		/* Default react sequence for initial entry  */
		enterSequence_Microwave_Idle_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_Open_Close_Door__entry_Default() {
		/* Default react sequence for initial entry  */
		enterSequence_Open_Close_Door_DoorClosed_default();
	}
	
	private long microwave_Idle_react(long transitioned_before) {
		/* The reactions of state Idle. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<0l) {
			if (high) {
				exitSequence_Microwave_Idle();
				enterSequence_Microwave_Mode_default();
				transitioned_after = 0l;
			} else {
				if (low) {
					exitSequence_Microwave_Idle();
					enterSequence_Microwave_Mode_alt_entry();
					transitioned_after = 0l;
				}
			}
		}
		return transitioned_after;
	}
	
	private long microwave_Cooking_react(long transitioned_before) {
		/* The reactions of state Cooking. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<0l) {
			if (open) {
				exitSequence_Microwave_Cooking();
				enterSequence_Microwave_Waiting_default();
				transitioned_after = 0l;
			} else {
				if (getRemainingTime()==0l) {
					exitSequence_Microwave_Cooking();
					enterSequence_Microwave_Finished_default();
					transitioned_after = 0l;
				} else {
					if (stop) {
						exitSequence_Microwave_Cooking();
						operationCallback.stopCook();
						operationCallback.beepOff();
						operationCallback.clearDisplay();
						enterSequence_Microwave_Idle_default();
						transitioned_after = 0l;
					}
				}
			}
		}
		/* If no transition was taken */
		if (transitioned_after==transitioned_before) {
			/* then execute local reactions. */
			if (((timeEvents[0]) && (getRemainingTime()>0l))) {
				operationCallback.displayTime(((((getRemainingTime() / 60l)) * 100l) + ((getRemainingTime() % 60l))));
				setRemainingTime(getRemainingTime() - 1l);
			}
		}
		return transitioned_after;
	}
	
	private long microwave_Mode_react(long transitioned_before) {
		/* The reactions of state Mode. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<0l) {
			if (timer) {
				exitSequence_Microwave_Mode();
				enterSequence_Microwave_SettingTime_default();
				transitioned_after = 0l;
			} else {
				if (stop) {
					exitSequence_Microwave_Mode();
					operationCallback.clearDisplay();
					enterSequence_Microwave_Idle_default();
					transitioned_after = 0l;
				}
			}
		}
		return transitioned_after;
	}
	
	private long microwave_Mode_r1_High_react(long transitioned_before) {
		/* The reactions of state High. */
		long transitioned_after = microwave_Mode_react(transitioned_before);
		if (transitioned_after<0l) {
			if (low) {
				exitSequence_Microwave_Mode_r1_High();
				enterSequence_Microwave_Mode_r1_Low_default();
				transitioned_after = 0l;
			}
		}
		return transitioned_after;
	}
	
	private long microwave_Mode_r1_Low_react(long transitioned_before) {
		/* The reactions of state Low. */
		long transitioned_after = microwave_Mode_react(transitioned_before);
		if (transitioned_after<0l) {
			if (high) {
				exitSequence_Microwave_Mode_r1_Low();
				enterSequence_Microwave_Mode_r1_High_default();
				transitioned_after = 0l;
			}
		}
		return transitioned_after;
	}
	
	private long microwave_Waiting_react(long transitioned_before) {
		/* The reactions of state Waiting. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<0l) {
			if (stop) {
				exitSequence_Microwave_Waiting();
				operationCallback.stopCook();
				operationCallback.beepOff();
				operationCallback.clearDisplay();
				enterSequence_Microwave_Idle_default();
				transitioned_after = 0l;
			} else {
				if (close) {
					exitSequence_Microwave_Waiting();
					enterSequence_Microwave_RestartCooking_default();
					transitioned_after = 0l;
				}
			}
		}
		return transitioned_after;
	}
	
	private long microwave_SettingTime_react(long transitioned_before) {
		/* The reactions of state SettingTime. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<0l) {
			if (((start) && ((getEnteredTime()>0l && getIsDoorClose())))) {
				exitSequence_Microwave_SettingTime();
				setRemainingTime(enteredTime);
				operationCallback.cook();
				enterSequence_Microwave_Cooking_default();
				transitioned_after = 0l;
			} else {
				if (stop) {
					exitSequence_Microwave_SettingTime();
					operationCallback.stopCook();
					operationCallback.beepOff();
					operationCallback.clearDisplay();
					enterSequence_Microwave_Idle_default();
					transitioned_after = 0l;
				}
			}
		}
		/* If no transition was taken */
		if (transitioned_after==transitioned_before) {
			/* then execute local reactions. */
			if (((digit) && (getEnteredTime()<1000l))) {
				setEnteredTime((((enteredTime * 10l)) + getDigitValue()));
				operationCallback.displayTime(((((getEnteredTime() / 60l)) * 100l) + ((getEnteredTime() % 60l))));
			}
		}
		return transitioned_after;
	}
	
	private long microwave_RestartCooking_react(long transitioned_before) {
		/* The reactions of state RestartCooking. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<0l) {
			if (((start) && (getIsDoorClose()))) {
				exitSequence_Microwave_RestartCooking();
				operationCallback.cook();
				enterSequence_Microwave_Cooking_default();
				transitioned_after = 0l;
			}
		}
		return transitioned_after;
	}
	
	private long microwave_Finished_react(long transitioned_before) {
		/* The reactions of state Finished. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<0l) {
			if (timeEvents[1]) {
				exitSequence_Microwave_Finished();
				operationCallback.beepOff();
				operationCallback.clearDisplay();
				timeEvents[1] = false;
				enterSequence_Microwave_Idle_default();
				transitioned_after = 0l;
			}
		}
		return transitioned_after;
	}
	
	private long microwave_Finished_r1_Bip_On_react(long transitioned_before) {
		/* The reactions of state Bip On. */
		long transitioned_after = microwave_Finished_react(transitioned_before);
		if (transitioned_after<0l) {
			if (timeEvents[2]) {
				exitSequence_Microwave_Finished_r1_Bip_On();
				timeEvents[2] = false;
				enterSequence_Microwave_Finished_r1_Bip_Off_default();
				transitioned_after = 0l;
			}
		}
		return transitioned_after;
	}
	
	private long microwave_Finished_r1_Bip_Off_react(long transitioned_before) {
		/* The reactions of state Bip Off. */
		long transitioned_after = microwave_Finished_react(transitioned_before);
		if (transitioned_after<0l) {
			if (timeEvents[3]) {
				exitSequence_Microwave_Finished_r1_Bip_Off();
				timeEvents[3] = false;
				enterSequence_Microwave_Finished_r1_Bip_On_default();
				transitioned_after = 0l;
			}
		}
		return transitioned_after;
	}
	
	private long open_Close_Door_DoorOpen_react(long transitioned_before) {
		/* The reactions of state DoorOpen. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<1l) {
			if (close) {
				exitSequence_Open_Close_Door_DoorOpen();
				enterSequence_Open_Close_Door_DoorClosed_default();
				transitioned_after = 1l;
			}
		}
		return transitioned_after;
	}
	
	private long open_Close_Door_DoorClosed_react(long transitioned_before) {
		/* The reactions of state DoorClosed. */
		long transitioned_after = transitioned_before;
		if (transitioned_after<1l) {
			if (open) {
				exitSequence_Open_Close_Door_DoorClosed();
				enterSequence_Open_Close_Door_DoorOpen_default();
				transitioned_after = 1l;
			}
		}
		return transitioned_after;
	}
	
	/* Can be used by the client code to trigger a run to completion step without raising an event. */
	public void triggerWithoutEvent() {
		runCycle();
	}
}
