/** Generated by YAKINDU Statechart Tools code generator. */
package microwave.microwave;

import microwave.ITimer;

public class MicrowaveStatemachine implements IMicrowaveStatemachine {
	protected class SCInterfaceImpl implements SCInterface {
	
		private SCInterfaceOperationCallback operationCallback;
		
		public void setSCInterfaceOperationCallback(
				SCInterfaceOperationCallback operationCallback) {
			this.operationCallback = operationCallback;
		}
		private boolean high;
		
		
		public void raiseHigh() {
			high = true;
			runCycle();
		}
		
		private boolean low;
		
		
		public void raiseLow() {
			low = true;
			runCycle();
		}
		
		private boolean digit;
		
		private long digitValue;
		
		
		public void raiseDigit(final long value) {
			digitValue = value;
			digit = true;
			runCycle();
		}
		protected long getDigitValue() {
			if (! digit ) 
				throw new IllegalStateException("Illegal event value access. Event Digit is not raised!");
			return digitValue;
		}
		
		private boolean timer;
		
		
		public void raiseTimer() {
			timer = true;
			runCycle();
		}
		
		private boolean start;
		
		
		public void raiseStart() {
			start = true;
			runCycle();
		}
		
		private boolean stop;
		
		
		public void raiseStop() {
			stop = true;
			runCycle();
		}
		
		private boolean open;
		
		
		public void raiseOpen() {
			open = true;
			runCycle();
		}
		
		private boolean close;
		
		
		public void raiseClose() {
			close = true;
			runCycle();
		}
		
		private long power;
		
		public long getPower() {
			return power;
		}
		
		public void setPower(long value) {
			this.power = value;
		}
		
		protected void clearEvents() {
			high = false;
			low = false;
			digit = false;
			timer = false;
			start = false;
			stop = false;
			open = false;
			close = false;
		}
	}
	
	
	protected SCInterfaceImpl sCInterface;
	
	private boolean initialized = false;
	
	public enum State {
		microwave_Idle,
		microwave_Cooking,
		microwave_Mode,
		microwave_Mode_r1_High,
		microwave_Mode_r1_Low,
		microwave_Waiting,
		microwave_SettingTime,
		microwave_RestartCooking,
		microwave_Finished,
		microwave_Finished_r1_Bip_On,
		microwave_Finished_r1_Bip_Off,
		open_Close_Door_DoorOpen,
		open_Close_Door_DoorClosed,
		$NullState$
	};
	
	private final State[] stateVector = new State[2];
	
	private int nextStateIndex;
	
	private ITimer timer;
	
	private final boolean[] timeEvents = new boolean[4];
	
	private long enteredTime;
	
	protected long getEnteredTime() {
		return enteredTime;
	}
	
	protected void setEnteredTime(long value) {
		this.enteredTime = value;
	}
	
	
	private boolean isDoorClose;
	
	protected boolean getIsDoorClose() {
		return isDoorClose;
	}
	
	protected void setIsDoorClose(boolean value) {
		this.isDoorClose = value;
	}
	
	
	private long remainingTime;
	
	protected long getRemainingTime() {
		return remainingTime;
	}
	
	protected void setRemainingTime(long value) {
		this.remainingTime = value;
	}
	
	
	public MicrowaveStatemachine() {
		sCInterface = new SCInterfaceImpl();
	}
	
	public void init() {
		this.initialized = true;
		if (timer == null) {
			throw new IllegalStateException("timer not set.");
		}
		if (this.sCInterface.operationCallback == null) {
			throw new IllegalStateException("Operation callback for interface sCInterface must be set.");
		}
		
		for (int i = 0; i < 2; i++) {
			stateVector[i] = State.$NullState$;
		}
		clearEvents();
		clearOutEvents();
		sCInterface.setPower(0);
		
		setEnteredTime(0);
		
		setIsDoorClose(true);
		
		setRemainingTime(0);
	}
	
	public void enter() {
		if (!initialized) {
			throw new IllegalStateException(
				"The state machine needs to be initialized first by calling the init() function."
			);
		}
		if (timer == null) {
			throw new IllegalStateException("timer not set.");
		}
		enterSequence_Microwave_default();
		enterSequence_Open_Close_Door_default();
	}
	
	public void runCycle() {
		if (!initialized)
			throw new IllegalStateException(
					"The state machine needs to be initialized first by calling the init() function.");
		clearOutEvents();
		for (nextStateIndex = 0; nextStateIndex < stateVector.length; nextStateIndex++) {
			switch (stateVector[nextStateIndex]) {
			case microwave_Idle:
				microwave_Idle_react(true);
				break;
			case microwave_Cooking:
				microwave_Cooking_react(true);
				break;
			case microwave_Mode_r1_High:
				microwave_Mode_r1_High_react(true);
				break;
			case microwave_Mode_r1_Low:
				microwave_Mode_r1_Low_react(true);
				break;
			case microwave_Waiting:
				microwave_Waiting_react(true);
				break;
			case microwave_SettingTime:
				microwave_SettingTime_react(true);
				break;
			case microwave_RestartCooking:
				microwave_RestartCooking_react(true);
				break;
			case microwave_Finished_r1_Bip_On:
				microwave_Finished_r1_Bip_On_react(true);
				break;
			case microwave_Finished_r1_Bip_Off:
				microwave_Finished_r1_Bip_Off_react(true);
				break;
			case open_Close_Door_DoorOpen:
				open_Close_Door_DoorOpen_react(true);
				break;
			case open_Close_Door_DoorClosed:
				open_Close_Door_DoorClosed_react(true);
				break;
			default:
				// $NullState$
			}
		}
		clearEvents();
	}
	public void exit() {
		exitSequence_Microwave();
		exitSequence_Open_Close_Door();
	}
	
	/**
	 * @see IStatemachine#isActive()
	 */
	public boolean isActive() {
		return stateVector[0] != State.$NullState$||stateVector[1] != State.$NullState$;
	}
	
	/** 
	* Always returns 'false' since this state machine can never become final.
	*
	* @see IStatemachine#isFinal()
	*/
	public boolean isFinal() {
		return false;
	}
	/**
	* This method resets the incoming events (time events included).
	*/
	protected void clearEvents() {
		sCInterface.clearEvents();
		for (int i=0; i<timeEvents.length; i++) {
			timeEvents[i] = false;
		}
	}
	
	/**
	* This method resets the outgoing events.
	*/
	protected void clearOutEvents() {
	}
	
	/**
	* Returns true if the given state is currently active otherwise false.
	*/
	public boolean isStateActive(State state) {
	
		switch (state) {
		case microwave_Idle:
			return stateVector[0] == State.microwave_Idle;
		case microwave_Cooking:
			return stateVector[0] == State.microwave_Cooking;
		case microwave_Mode:
			return stateVector[0].ordinal() >= State.
					microwave_Mode.ordinal()&& stateVector[0].ordinal() <= State.microwave_Mode_r1_Low.ordinal();
		case microwave_Mode_r1_High:
			return stateVector[0] == State.microwave_Mode_r1_High;
		case microwave_Mode_r1_Low:
			return stateVector[0] == State.microwave_Mode_r1_Low;
		case microwave_Waiting:
			return stateVector[0] == State.microwave_Waiting;
		case microwave_SettingTime:
			return stateVector[0] == State.microwave_SettingTime;
		case microwave_RestartCooking:
			return stateVector[0] == State.microwave_RestartCooking;
		case microwave_Finished:
			return stateVector[0].ordinal() >= State.
					microwave_Finished.ordinal()&& stateVector[0].ordinal() <= State.microwave_Finished_r1_Bip_Off.ordinal();
		case microwave_Finished_r1_Bip_On:
			return stateVector[0] == State.microwave_Finished_r1_Bip_On;
		case microwave_Finished_r1_Bip_Off:
			return stateVector[0] == State.microwave_Finished_r1_Bip_Off;
		case open_Close_Door_DoorOpen:
			return stateVector[1] == State.open_Close_Door_DoorOpen;
		case open_Close_Door_DoorClosed:
			return stateVector[1] == State.open_Close_Door_DoorClosed;
		default:
			return false;
		}
	}
	
	/**
	* Set the {@link ITimer} for the state machine. It must be set
	* externally on a timed state machine before a run cycle can be correctly
	* executed.
	* 
	* @param timer
	*/
	public void setTimer(ITimer timer) {
		this.timer = timer;
	}
	
	/**
	* Returns the currently used timer.
	* 
	* @return {@link ITimer}
	*/
	public ITimer getTimer() {
		return timer;
	}
	
	public void timeElapsed(int eventID) {
		timeEvents[eventID] = true;
		runCycle();
	}
	
	public SCInterface getSCInterface() {
		return sCInterface;
	}
	
	public void raiseHigh() {
		sCInterface.raiseHigh();
	}
	
	public void raiseLow() {
		sCInterface.raiseLow();
	}
	
	public void raiseDigit(long value) {
		sCInterface.raiseDigit(value);
	}
	
	public void raiseTimer() {
		sCInterface.raiseTimer();
	}
	
	public void raiseStart() {
		sCInterface.raiseStart();
	}
	
	public void raiseStop() {
		sCInterface.raiseStop();
	}
	
	public void raiseOpen() {
		sCInterface.raiseOpen();
	}
	
	public void raiseClose() {
		sCInterface.raiseClose();
	}
	
	public long getPower() {
		return sCInterface.getPower();
	}
	
	public void setPower(long value) {
		sCInterface.setPower(value);
	}
	
	/* Entry action for state 'Cooking'. */
	private void entryAction_Microwave_Cooking() {
		timer.setTimer(this, 0, (1 * 1000), true);
	}
	
	/* Entry action for state 'High'. */
	private void entryAction_Microwave_Mode_r1_High() {
		sCInterface.setPower(1);
		
		sCInterface.operationCallback.display("High");
	}
	
	/* Entry action for state 'Low'. */
	private void entryAction_Microwave_Mode_r1_Low() {
		sCInterface.setPower(2);
		
		sCInterface.operationCallback.display("Low");
	}
	
	/* Entry action for state 'Waiting'. */
	private void entryAction_Microwave_Waiting() {
		sCInterface.operationCallback.display("Waiting");
		
		sCInterface.operationCallback.stopCook();
	}
	
	/* Entry action for state 'SettingTime'. */
	private void entryAction_Microwave_SettingTime() {
		setEnteredTime(0);
		
		sCInterface.operationCallback.displayTime(0);
	}
	
	/* Entry action for state 'RestartCooking'. */
	private void entryAction_Microwave_RestartCooking() {
		sCInterface.operationCallback.displayTime(((((getRemainingTime() / 60)) * 100) + ((getRemainingTime() % 60))));
	}
	
	/* Entry action for state 'Finished'. */
	private void entryAction_Microwave_Finished() {
		timer.setTimer(this, 1, (5 * 1000), false);
		
		sCInterface.operationCallback.display("Finished");
		
		sCInterface.operationCallback.stopCook();
	}
	
	/* Entry action for state 'Bip On'. */
	private void entryAction_Microwave_Finished_r1_Bip_On() {
		timer.setTimer(this, 2, 500, false);
		
		sCInterface.operationCallback.beepOn();
	}
	
	/* Entry action for state 'Bip Off'. */
	private void entryAction_Microwave_Finished_r1_Bip_Off() {
		timer.setTimer(this, 3, 500, false);
		
		sCInterface.operationCallback.beepOff();
	}
	
	/* Entry action for state 'DoorOpen'. */
	private void entryAction_Open_Close_Door_DoorOpen() {
		sCInterface.operationCallback.openDoor();
		
		setIsDoorClose(false);
	}
	
	/* Entry action for state 'DoorClosed'. */
	private void entryAction_Open_Close_Door_DoorClosed() {
		sCInterface.operationCallback.closeDoor();
		
		setIsDoorClose(true);
	}
	
	/* Exit action for state 'Cooking'. */
	private void exitAction_Microwave_Cooking() {
		timer.unsetTimer(this, 0);
	}
	
	/* Exit action for state 'Finished'. */
	private void exitAction_Microwave_Finished() {
		timer.unsetTimer(this, 1);
	}
	
	/* Exit action for state 'Bip On'. */
	private void exitAction_Microwave_Finished_r1_Bip_On() {
		timer.unsetTimer(this, 2);
	}
	
	/* Exit action for state 'Bip Off'. */
	private void exitAction_Microwave_Finished_r1_Bip_Off() {
		timer.unsetTimer(this, 3);
	}
	
	/* 'default' enter sequence for state Idle */
	private void enterSequence_Microwave_Idle_default() {
		nextStateIndex = 0;
		stateVector[0] = State.microwave_Idle;
	}
	
	/* 'default' enter sequence for state Cooking */
	private void enterSequence_Microwave_Cooking_default() {
		entryAction_Microwave_Cooking();
		nextStateIndex = 0;
		stateVector[0] = State.microwave_Cooking;
	}
	
	/* 'alt_entry' enter sequence for state Mode */
	private void enterSequence_Microwave_Mode_alt_entry() {
		enterSequence_Microwave_Mode_r1_alt_entry();
	}
	
	/* 'default' enter sequence for state Mode */
	private void enterSequence_Microwave_Mode_default() {
		enterSequence_Microwave_Mode_r1_default();
	}
	
	/* 'default' enter sequence for state High */
	private void enterSequence_Microwave_Mode_r1_High_default() {
		entryAction_Microwave_Mode_r1_High();
		nextStateIndex = 0;
		stateVector[0] = State.microwave_Mode_r1_High;
	}
	
	/* 'default' enter sequence for state Low */
	private void enterSequence_Microwave_Mode_r1_Low_default() {
		entryAction_Microwave_Mode_r1_Low();
		nextStateIndex = 0;
		stateVector[0] = State.microwave_Mode_r1_Low;
	}
	
	/* 'default' enter sequence for state Waiting */
	private void enterSequence_Microwave_Waiting_default() {
		entryAction_Microwave_Waiting();
		nextStateIndex = 0;
		stateVector[0] = State.microwave_Waiting;
	}
	
	/* 'default' enter sequence for state SettingTime */
	private void enterSequence_Microwave_SettingTime_default() {
		entryAction_Microwave_SettingTime();
		nextStateIndex = 0;
		stateVector[0] = State.microwave_SettingTime;
	}
	
	/* 'default' enter sequence for state RestartCooking */
	private void enterSequence_Microwave_RestartCooking_default() {
		entryAction_Microwave_RestartCooking();
		nextStateIndex = 0;
		stateVector[0] = State.microwave_RestartCooking;
	}
	
	/* 'default' enter sequence for state Finished */
	private void enterSequence_Microwave_Finished_default() {
		entryAction_Microwave_Finished();
		enterSequence_Microwave_Finished_r1_default();
	}
	
	/* 'default' enter sequence for state Bip On */
	private void enterSequence_Microwave_Finished_r1_Bip_On_default() {
		entryAction_Microwave_Finished_r1_Bip_On();
		nextStateIndex = 0;
		stateVector[0] = State.microwave_Finished_r1_Bip_On;
	}
	
	/* 'default' enter sequence for state Bip Off */
	private void enterSequence_Microwave_Finished_r1_Bip_Off_default() {
		entryAction_Microwave_Finished_r1_Bip_Off();
		nextStateIndex = 0;
		stateVector[0] = State.microwave_Finished_r1_Bip_Off;
	}
	
	/* 'default' enter sequence for state DoorOpen */
	private void enterSequence_Open_Close_Door_DoorOpen_default() {
		entryAction_Open_Close_Door_DoorOpen();
		nextStateIndex = 1;
		stateVector[1] = State.open_Close_Door_DoorOpen;
	}
	
	/* 'default' enter sequence for state DoorClosed */
	private void enterSequence_Open_Close_Door_DoorClosed_default() {
		entryAction_Open_Close_Door_DoorClosed();
		nextStateIndex = 1;
		stateVector[1] = State.open_Close_Door_DoorClosed;
	}
	
	/* 'default' enter sequence for region Microwave */
	private void enterSequence_Microwave_default() {
		react_Microwave__entry_Default();
	}
	
	/* 'default' enter sequence for region r1 */
	private void enterSequence_Microwave_Mode_r1_default() {
		react_Microwave_Mode_r1__entry_Default();
	}
	
	/* 'alt_entry' enter sequence for region r1 */
	private void enterSequence_Microwave_Mode_r1_alt_entry() {
		react_Microwave_Mode_r1_alt_entry();
	}
	
	/* 'default' enter sequence for region r1 */
	private void enterSequence_Microwave_Finished_r1_default() {
		react_Microwave_Finished_r1__entry_Default();
	}
	
	/* 'default' enter sequence for region Open/Close Door */
	private void enterSequence_Open_Close_Door_default() {
		react_Open_Close_Door__entry_Default();
	}
	
	/* Default exit sequence for state Idle */
	private void exitSequence_Microwave_Idle() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state Cooking */
	private void exitSequence_Microwave_Cooking() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
		
		exitAction_Microwave_Cooking();
	}
	
	/* Default exit sequence for state Mode */
	private void exitSequence_Microwave_Mode() {
		exitSequence_Microwave_Mode_r1();
	}
	
	/* Default exit sequence for state High */
	private void exitSequence_Microwave_Mode_r1_High() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state Low */
	private void exitSequence_Microwave_Mode_r1_Low() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state Waiting */
	private void exitSequence_Microwave_Waiting() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state SettingTime */
	private void exitSequence_Microwave_SettingTime() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state RestartCooking */
	private void exitSequence_Microwave_RestartCooking() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
	}
	
	/* Default exit sequence for state Finished */
	private void exitSequence_Microwave_Finished() {
		exitSequence_Microwave_Finished_r1();
		exitAction_Microwave_Finished();
	}
	
	/* Default exit sequence for state Bip On */
	private void exitSequence_Microwave_Finished_r1_Bip_On() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
		
		exitAction_Microwave_Finished_r1_Bip_On();
	}
	
	/* Default exit sequence for state Bip Off */
	private void exitSequence_Microwave_Finished_r1_Bip_Off() {
		nextStateIndex = 0;
		stateVector[0] = State.$NullState$;
		
		exitAction_Microwave_Finished_r1_Bip_Off();
	}
	
	/* Default exit sequence for state DoorOpen */
	private void exitSequence_Open_Close_Door_DoorOpen() {
		nextStateIndex = 1;
		stateVector[1] = State.$NullState$;
	}
	
	/* Default exit sequence for state DoorClosed */
	private void exitSequence_Open_Close_Door_DoorClosed() {
		nextStateIndex = 1;
		stateVector[1] = State.$NullState$;
	}
	
	/* Default exit sequence for region Microwave */
	private void exitSequence_Microwave() {
		switch (stateVector[0]) {
		case microwave_Idle:
			exitSequence_Microwave_Idle();
			break;
		case microwave_Cooking:
			exitSequence_Microwave_Cooking();
			break;
		case microwave_Mode_r1_High:
			exitSequence_Microwave_Mode_r1_High();
			break;
		case microwave_Mode_r1_Low:
			exitSequence_Microwave_Mode_r1_Low();
			break;
		case microwave_Waiting:
			exitSequence_Microwave_Waiting();
			break;
		case microwave_SettingTime:
			exitSequence_Microwave_SettingTime();
			break;
		case microwave_RestartCooking:
			exitSequence_Microwave_RestartCooking();
			break;
		case microwave_Finished_r1_Bip_On:
			exitSequence_Microwave_Finished_r1_Bip_On();
			exitAction_Microwave_Finished();
			break;
		case microwave_Finished_r1_Bip_Off:
			exitSequence_Microwave_Finished_r1_Bip_Off();
			exitAction_Microwave_Finished();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region r1 */
	private void exitSequence_Microwave_Mode_r1() {
		switch (stateVector[0]) {
		case microwave_Mode_r1_High:
			exitSequence_Microwave_Mode_r1_High();
			break;
		case microwave_Mode_r1_Low:
			exitSequence_Microwave_Mode_r1_Low();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region r1 */
	private void exitSequence_Microwave_Finished_r1() {
		switch (stateVector[0]) {
		case microwave_Finished_r1_Bip_On:
			exitSequence_Microwave_Finished_r1_Bip_On();
			break;
		case microwave_Finished_r1_Bip_Off:
			exitSequence_Microwave_Finished_r1_Bip_Off();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region Open/Close Door */
	private void exitSequence_Open_Close_Door() {
		switch (stateVector[1]) {
		case open_Close_Door_DoorOpen:
			exitSequence_Open_Close_Door_DoorOpen();
			break;
		case open_Close_Door_DoorClosed:
			exitSequence_Open_Close_Door_DoorClosed();
			break;
		default:
			break;
		}
	}
	
	/* Default react sequence for initial entry  */
	private void react_Microwave_Mode_r1__entry_Default() {
		enterSequence_Microwave_Mode_r1_High_default();
	}
	
	/* Default react sequence for initial entry alt_entry */
	private void react_Microwave_Mode_r1_alt_entry() {
		enterSequence_Microwave_Mode_r1_Low_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_Microwave_Finished_r1__entry_Default() {
		enterSequence_Microwave_Finished_r1_Bip_On_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_Microwave__entry_Default() {
		enterSequence_Microwave_Idle_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_Open_Close_Door__entry_Default() {
		enterSequence_Open_Close_Door_DoorClosed_default();
	}
	
	private boolean react() {
		return false;
	}
	
	private boolean microwave_Idle_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (react()==false) {
				if (sCInterface.high) {
					exitSequence_Microwave_Idle();
					enterSequence_Microwave_Mode_default();
				} else {
					if (sCInterface.low) {
						exitSequence_Microwave_Idle();
						enterSequence_Microwave_Mode_alt_entry();
					} else {
						did_transition = false;
					}
				}
			}
		}
		return did_transition;
	}
	
	private boolean microwave_Cooking_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (react()==false) {
				if (sCInterface.open) {
					exitSequence_Microwave_Cooking();
					enterSequence_Microwave_Waiting_default();
				} else {
					if (getRemainingTime()==0) {
						exitSequence_Microwave_Cooking();
						enterSequence_Microwave_Finished_default();
					} else {
						if (sCInterface.stop) {
							exitSequence_Microwave_Cooking();
							sCInterface.operationCallback.stopCook();
							
							sCInterface.operationCallback.beepOff();
							
							sCInterface.operationCallback.clearDisplay();
							
							enterSequence_Microwave_Idle_default();
						} else {
							did_transition = false;
						}
					}
				}
			}
		}
		if (did_transition==false) {
			if (((timeEvents[0]) && (getRemainingTime()>0))) {
				sCInterface.operationCallback.displayTime(((((getRemainingTime() / 60)) * 100) + ((getRemainingTime() % 60))));
				
				setRemainingTime(getRemainingTime() - 1);
			}
		}
		return did_transition;
	}
	
	private boolean microwave_Mode_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (react()==false) {
				if (sCInterface.timer) {
					exitSequence_Microwave_Mode();
					enterSequence_Microwave_SettingTime_default();
				} else {
					if (sCInterface.stop) {
						exitSequence_Microwave_Mode();
						sCInterface.operationCallback.clearDisplay();
						
						enterSequence_Microwave_Idle_default();
					} else {
						did_transition = false;
					}
				}
			}
		}
		return did_transition;
	}
	
	private boolean microwave_Mode_r1_High_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (microwave_Mode_react(try_transition)==false) {
				if (sCInterface.low) {
					exitSequence_Microwave_Mode_r1_High();
					enterSequence_Microwave_Mode_r1_Low_default();
				} else {
					did_transition = false;
				}
			}
		}
		return did_transition;
	}
	
	private boolean microwave_Mode_r1_Low_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (microwave_Mode_react(try_transition)==false) {
				if (sCInterface.high) {
					exitSequence_Microwave_Mode_r1_Low();
					enterSequence_Microwave_Mode_r1_High_default();
				} else {
					did_transition = false;
				}
			}
		}
		return did_transition;
	}
	
	private boolean microwave_Waiting_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (react()==false) {
				if (sCInterface.stop) {
					exitSequence_Microwave_Waiting();
					sCInterface.operationCallback.stopCook();
					
					sCInterface.operationCallback.beepOff();
					
					sCInterface.operationCallback.clearDisplay();
					
					enterSequence_Microwave_Idle_default();
				} else {
					if (sCInterface.close) {
						exitSequence_Microwave_Waiting();
						enterSequence_Microwave_RestartCooking_default();
					} else {
						did_transition = false;
					}
				}
			}
		}
		return did_transition;
	}
	
	private boolean microwave_SettingTime_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (react()==false) {
				if (((sCInterface.start) && ((getEnteredTime()>0 && getIsDoorClose())))) {
					exitSequence_Microwave_SettingTime();
					setRemainingTime(enteredTime);
					
					sCInterface.operationCallback.cook();
					
					enterSequence_Microwave_Cooking_default();
				} else {
					if (sCInterface.stop) {
						exitSequence_Microwave_SettingTime();
						sCInterface.operationCallback.stopCook();
						
						sCInterface.operationCallback.beepOff();
						
						sCInterface.operationCallback.clearDisplay();
						
						enterSequence_Microwave_Idle_default();
					} else {
						did_transition = false;
					}
				}
			}
		}
		if (did_transition==false) {
			if (((sCInterface.digit) && (getEnteredTime()<1000))) {
				setEnteredTime((((enteredTime * 10)) + sCInterface.getDigitValue()));
				
				sCInterface.operationCallback.displayTime(((((getEnteredTime() / 60)) * 100) + ((getEnteredTime() % 60))));
			}
		}
		return did_transition;
	}
	
	private boolean microwave_RestartCooking_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (react()==false) {
				if (((sCInterface.start) && (getIsDoorClose()))) {
					exitSequence_Microwave_RestartCooking();
					sCInterface.operationCallback.cook();
					
					enterSequence_Microwave_Cooking_default();
				} else {
					did_transition = false;
				}
			}
		}
		return did_transition;
	}
	
	private boolean microwave_Finished_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (react()==false) {
				if (timeEvents[1]) {
					exitSequence_Microwave_Finished();
					sCInterface.operationCallback.beepOff();
					
					sCInterface.operationCallback.clearDisplay();
					
					enterSequence_Microwave_Idle_default();
				} else {
					did_transition = false;
				}
			}
		}
		return did_transition;
	}
	
	private boolean microwave_Finished_r1_Bip_On_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (microwave_Finished_react(try_transition)==false) {
				if (timeEvents[2]) {
					exitSequence_Microwave_Finished_r1_Bip_On();
					enterSequence_Microwave_Finished_r1_Bip_Off_default();
				} else {
					did_transition = false;
				}
			}
		}
		return did_transition;
	}
	
	private boolean microwave_Finished_r1_Bip_Off_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (microwave_Finished_react(try_transition)==false) {
				if (timeEvents[3]) {
					exitSequence_Microwave_Finished_r1_Bip_Off();
					enterSequence_Microwave_Finished_r1_Bip_On_default();
				} else {
					did_transition = false;
				}
			}
		}
		return did_transition;
	}
	
	private boolean open_Close_Door_DoorOpen_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.close) {
				exitSequence_Open_Close_Door_DoorOpen();
				enterSequence_Open_Close_Door_DoorClosed_default();
			} else {
				did_transition = false;
			}
		}
		return did_transition;
	}
	
	private boolean open_Close_Door_DoorClosed_react(boolean try_transition) {
		boolean did_transition = try_transition;
		
		if (try_transition) {
			if (sCInterface.open) {
				exitSequence_Open_Close_Door_DoorClosed();
				enterSequence_Open_Close_Door_DoorOpen_default();
			} else {
				did_transition = false;
			}
		}
		return did_transition;
	}
	
}
